# Author: baichen.bai@alibaba-inc.com


## working mode specifications
# initialize | simulation | dataset-generation | exploration
# initialize: initialize the data set using RTED
mode: simulation


## design space specifications
design-space: design-space/design-space.xlsx


## simulation specifications
simulation:
  simulator:
    # gem5-research root path
    gem5-research-root: /root/workspace/arch-explorer/infras/gem5-research
    # choose the simulator to run
    start-idx: ~
    end-idx: ~
    candidate-idx: ~
    # select designs from design dataset
    candidate-design-set: ~
    candidate-embedding:
      - [8, 64, 24, 2048, 4096, 4096, 24, 2048, 160, 176, 176, 48, 32, 24, 5, 2, 2, 1, 64, 4, 16, 4]
      - [8, 64, 24, 2048, 4096, 4096, 24, 2048, 144, 160, 160, 48, 32, 28, 5, 2, 1, 1, 64, 4, 32, 4]
      - [8, 64, 24, 2048, 4096, 4096, 24, 2048, 128, 144, 144, 48, 32, 32, 5, 2, 1, 1, 64, 4, 64, 4]
      - [8, 64, 24, 2048, 4096, 4096, 24, 2048, 128, 128, 128, 48, 32, 36, 5, 2, 1, 1, 64, 4, 16, 4]
      - [8, 64, 24, 2048, 4096, 4096, 24, 2048, 128, 112, 112, 48, 32, 40, 5, 2, 1, 1, 64, 4, 16, 4]
      - [8, 64, 24, 2048, 4096, 4096, 24, 2048, 128, 112, 96, 48, 32, 44, 5, 2, 1, 1, 64, 4, 16, 4]
  # benchmark specifications
  benchmark:
    # choose the benchmark to run
    run: spec2017
    spec2006:
      benchmark-root: ~
      candidate: ~
      # since we have no simpoints for SPEC2006, we use different max-insts
      # to test the benchmark. Fewer instructions are used in DSE.
      dse: False
    spec2017:
      benchmark-root: /root/workspace/benchmarks/spec2017/spec2017
      checkpoint-root: /root/workspace/benchmarks/spec2017/checkpoint
      # maximum instruction
      max-insts: ~
      candidate: ~
    bare-model:
      warmup-insts: ~
      fast-forward: ~
      candidate: ~
  misc-setting:
    # True: use the new DEG to model, False: disable DEG modeling
    deg-model: False
    # True: enable visualization for DEG, False: disable visualization
    vis: False
    # specify the instruction sequence to view
    # the index is started with 1
    start-idx: ~
    end-idx: ~
