# Author: baichen.bai@alibaba-inc.com


## working mode specifications
# simulation | exploration
mode: exploration


## design space specifications
design-space: design-space/design-space.xlsx


## simulation specifications
simulation:
  simulator:
    # gem5-research root path
    gem5-research-root: /root/workspace/arch-explorer/infras/gem5-research
    # choose the simulator to run
    start-idx: ~
    end-idx: ~
    candidate-idx: ~
    # select designs from design dataset
    candidate-design-set: ~
    candidate-embedding: ~
  # benchmark specifications
  benchmark:
    # choose the benchmark to run
    run: spec2006
    spec2006:
      benchmark-root: /root/workspace/benchmarks/spec2006
      candidate:
        - 401.bzip2
        - 429.mcf
        - 456.hmmer
        - 458.sjeng
        - 462.libquantum
        - 471.omnetpp
        - 483.xalancbmk
        - 444.namd
        - 447.dealII
        - 450.soplex
        - 453.povray
      # since we have no simpoints for SPEC2006, we use different max-insts
      # to test the benchmark. Fewer instructions are used in DSE.
      dse: True
    spec2017:
      benchmark-root: ~
      checkpoint-root: ~
      # maximum instruction
      max-insts: ~
      candidate: ~
    bare-model:
      warmup-insts: ~
      fast-forward: ~
      candidate: ~
  misc-setting:
    # True: use the new DEG to model, False: disable DEG modeling
    deg-model: True
    # True: enable visualization for DEG, False: disable visualization
    vis: False
    # specify the instruction sequence to view
    # the index is started with 1
    start-idx: ~
    end-idx: ~


dse:
  # random seed
  seed: 42
  # how many hardware resource do we need to increase at each round
  top-k: 3
  # the number of threads to search
  # currently, `epoch` = 1
  epoch: 10
  # the maximal iterations for each thread
  budget: 15
  # we can specifiy the initial design index
  initial-design: ~
  pipeline-width:
    - 8
  # early stopping criterion
  early-stopping: 5
  output: report
