name: micro23
channels:
  - conda-forge
dependencies:
  - python=3.8.0
  - pip: 
    - numpy==1.23.4
    - pyyaml==6.0
    - torch==1.12.0
    - pandas==2.0.3
    - scikit-learn==1.1.2
    - openpyxl==3.1.2
    - scons==4.3.0
    - tqdm==4.64.1
    - gpytorch==1.6.0
    - botorch==0.6.0
    - matplotlib==3.6.1
    - networkx==2.8.7
    - graphviz==0.20.1
    - sklearn==0.0
